### ISSUE TITLE
Dask Version Checklist

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#251]
- [ ] RIME Pipeline Configuration
  - [x] Tensorflow Op Configurability.  The CreateAntennaJones and SumCoherencies ops  can now be given flags  defining which terms exists and are multiplied into the RIME in  their respective locations.
  - [ ] Pipeline Configuration. Need to come up with dictionary definitions for the different terms. This should describe their
      - locations in the pipeline.
      - inputs for memory budgeting. e.g. `{ 'lm': (nsrc, 2) }`
      - outputs for memory budgeting. e.g. `{ 'complex_phase': (nsrc, ntime, na, nchan) }`

- [x] xarray dataset from Measurement Set (available in https://github.com/ska-sa/xarray-ms/).
- [x] xarray dataset from FITS file (available in https://github.com/ska-sa/xarray-fits/).
- [ ] Input xarray dataset. Massage MS and FITS datasets into Montblanc dataset.
- [ ] Use tensorflow [Dataset API](https://www.tensorflow.org/versions/master/programmers_guide/datasets) for input into the tensorflow graph. The StagingArea/Queues are complicated and unwieldy and the Dataset API now has a GPU [prefetch](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/data/python/ops/prefetching_ops.py)

**Comment by sjperkins** [comment]
Closed in favour of #252
